name: first2apply-monorepo

services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro

    networks:
      - backend
    depends_on:
      - packages

  packages:
    image: node:22-trixie
    init: true
    # depends_on:
    #   - rabbitmq
    #   - mysql
    volumes:
      - ./:/first2apply
      - /first2apply/.nx/cache
      - /first2apply/.pnpm-store
      # Create anonymous volumes for any nested node_modules to isolate them
      - nodeModules:/first2apply/node_modules # Use named volume for root
      - /first2apply/apps/*/node_modules
    working_dir: /first2apply
    networks:
      - backend
    expose:
      - 3000
      - 3001
      - 3002
    # ports:
    #   - '3000:3000'
    #   - '3001:3001'
    env_file:
      - .env.example
      - .env
    command: sh -x -c "npm i -g pnpm && pnpm i --frozen-lockfile --force && npx nx run-many -t dev --parallel --maxParallel=5"

networks:
  backend:

volumes:
  nodeModules:
    driver: local
