packages:
  - apps/*
  - libraries/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - aws-sdk
  - contentlayer
  - contentlayer2
  - core-js
  - electron
  - electron-forge
  - electron-winstaller
  - esbuild
  - fs-xattr
  - macos-alias
  - nx
  - protobufjs
  - sharp
  - spawn-sync
  - supabase
  - unrs-resolver

overrides:
  '@conventional-changelog/git-client@<2.0.0': '>=2.0.0'
  '@octokit/plugin-paginate-rest@>=9.3.0-beta.1 <11.4.1': '>=11.4.1'
  '@opentelemetry/api': 1.4.1
  '@opentelemetry/core': 1.13.0
  '@opentelemetry/exporter-trace-otlp-grpc': 0.39.1
  '@opentelemetry/resources': 1.13.0
  '@opentelemetry/sdk-trace-base': 1.13.0
  '@opentelemetry/sdk-trace-node': 1.13.0
  '@opentelemetry/semantic-conventions': 1.13.0
  image-size@>=2.0.0 <2.0.2: '>=2.0.2'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  next@>=16.0.0-canary.0 <16.0.7: '>=16.0.7'
  node-forge@<1.3.2: '>=1.3.2'
  semver@>=7.0.0 <7.5.2: '>=7.5.2'
  tar@=7.5.1: '>=7.5.2'
  tmp@<=0.2.3: '>=0.2.4'
  webpack-dev-server@<=5.2.0: '>=5.2.1'
