packages:
  - apps/*
  - libraries/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - aws-sdk
  - contentlayer
  - contentlayer2
  - core-js
  - electron
  - electron-forge
  - electron-winstaller
  - esbuild
  - fs-xattr
  - macos-alias
  - nx
  - protobufjs
  - sharp
  - spawn-sync
  - supabase
  - unrs-resolver
