name: Microsoft Store Release

on:
  push:
    tags:
      - 'store-v*'

jobs:
  build-store:
    runs-on: windows-latest
    environment: Production
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          cd desktopProbe
          npm ci
          
      - name: Build APPX
        env:
          APP_BUNDLE_ID: ${{ secrets.APP_BUNDLE_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          MEZMO_API_KEY: ${{ secrets.MEZMO_API_KEY }}
          AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
        run: |
          cd desktopProbe
          npm run build:win
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          
      - name: Upload to S3
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          # Get the version from package.json
          VERSION=$(node -p "require('./desktopProbe/package.json').version")
          
          # Upload DEB file
          aws s3 cp desktopProbe/out/make/deb/x64/*.deb \
            s3://${S3_BUCKET_NAME}/releases/win32/x64/first2apply-${VERSION}-x64.appx \
            --acl public-read
          
      - name: Update latest symlinks
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          VERSION=$(node -p "require('./desktopProbe/package.json').version")
          
          # Create "latest" versions for easy linking
          aws s3 cp s3://${S3_BUCKET_NAME}/releases/win/x64/first2apply-${VERSION}-amd64.deb \
            s3://${S3_BUCKET_NAME}/releases/win32/x64/first2apply-latest-amd64.deb \
            --acl public-read

          aws s3 cp s3://${S3_BUCKET_NAME}/releases/win/x64/first2apply-${VERSION}.x86_64.rpm \
            s3://${S3_BUCKET_NAME}/releases/win32/x64/first2apply-latest.x86_64.rpm \
            --acl public-read